### ISSUE TITLE
img and SQL

### ISSUE THREAD

**Issue by meetcsworld** [linzworld/iDouban#1]
服务器上的内容加载不出来 。  可以发一下SQL和图片吗  邮箱: 2015459859@qq.com

**Comment by linzworld** [comment]
您好，现在图片都是放到服务器上的，已经修复好可以访问服务器获取，同时我也把对应的图片同步放在了WebContent\image目录下，sql文件也放在了根目录的sql文件夹下，欢迎交流学习!
